coverage:
  status:
    project:
      unit:
        informational: true
      e2e:
        informational: true
    patch:
      unit:
        informational: true
      e2e:
        informational: true
