networks:
  console:

services:
  console:
    image: ${CONSOLE_IMAGE}
    ports:
      - "8087:8080"
    environment:
      GODEBUG: fips140=off
    command:
      - "--tuf-repo-url=https://tuf-repo-cdn.sigstore.dev"
    networks:
      - console
  
  console-ui:
    image: ${CONSOLE_UI_IMAGE}
    environment:
      CONSOLE_API_URL: http://console:8080
    ports:
      - "8088:8080"
    networks:
      - console
    depends_on:
      console:
        condition: service_started
  
  playwright:
    image: mcr.microsoft.com/playwright:v1.59.0-jammy
    ports:
      - "5000:5000"
    network_mode: host
    working_dir: /home/pwuser
    command:
      - /bin/sh
      - -c
      - npx -y playwright@1.59.0 run-server --port 5000

