apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trusted-artifact-signer

resources:
  - console-serviceaccounts.yaml
  # Backend
  - console-backend-deploy.yaml
  - console-backend-service.yaml
  # UI
  - console-ui-deploy.yaml
  - console-ui-service.yaml
  - console-ui-route.yaml
