name: Start console
description: Start console using docker compose.
inputs:
  ui_image:
    description: image uri for the ui (ie. ghcr.io/<namespace>/<image-name>:<tag>)
    type: string
    required: false
    default: ""
  server_image:
    description: image uri for the server (ie. ghcr.io/<namespace>/<image-name>:<tag>)
    type: string
    required: false
    default: ""
  server_db_image:
    description: image uri for the database (ie. ghcr.io/<namespace>/<image-name>:<tag>)
    type: string
    required: false
    default: ""
  playwright_version:
    description: version of the playwright image to run
    type: string
    required: false
    default: ""
outputs:
  server_port:
    description: Port where the server is running
    value: ${{ steps.set-output.outputs.server_port }}
  ui_port:
    description: Port where the UI is running
    value: ${{ steps.set-output.outputs.ui_port }}
  playwright_port:
    description: Port where the Playwright server is running
    value: ${{ steps.set-output.outputs.playwright_port }}
runs:
  using: "composite"
  steps:
    - name: Start console
      working-directory: ${{ github.action_path }}/../../..
      shell: bash
      run: |
        opts=""

        if [ -n "${{ inputs.server_image }}" ]; then
          opts="${opts} CONSOLE_IMAGE=${{ inputs.server_image }}"
        fi
        if [ -n "${{ inputs.ui_image }}" ]; then
          opts="${opts} CONSOLE_UI_IMAGE=${{ inputs.ui_image }}"
        fi
        if [ -n "${{ inputs.server_db_image }}" ]; then
          opts="${opts} CONSOLE_DB_IMAGE=${{ inputs.server_db_image }}"
        fi

        if [ -n "${{ inputs.playwright_version }}" ]; then
          opts="${opts} PLAYWRIGHT_VERSION=${{ inputs.playwright_version }}"
        fi

        echo "opts: $opts"

        eval "${opts} docker compose up -d"

    - name: Wait for services to be ready
      shell: bash
      run: |
        # Wait for backend
        until curl -s http://localhost:8087/healthz | jq -e '.status == "ok"' >/dev/null 2>&1; do
          echo "Waiting for healthy service response on port 8087..."
          sleep 2
        done
        
        # Wait for ui
        until curl -s http://localhost:8088 | grep -qi "<html"; do
          echo "Waiting for HTML page on port 8088..."
          sleep 2
        done

    - id: set-output
      shell: bash
      run: |
        echo "server_port=8087" >> $GITHUB_OUTPUT
        echo "ui_port=8088" >> $GITHUB_OUTPUT
        echo "playwright_port=5000" >> $GITHUB_OUTPUT
